import turtle
t=turtle.Turtle()
wn=turtle.Screen()
wn.bgcolor("black")
t.speed(1)
t.color("red")
t.begin_fill()
t.fillcolor("red")
t.lt(140)
t.forward(180)
t.circle(-90,200)
t.setheading(60)
t.circle(-90,200)
t.forward(180)
t.end_fill()
t.hideturtle()